" vimrc files from @jibone
" http://jshamsul.com

" Use Vim settings, and not Vi settings. Must be as early as posible,
" It has side effects.
set nocompatible

" Map the leader key
let mapleader = "\<Space>"

" Reload vimrc
nmap <leader>so :source $MYVIMRC<cr>

" Source defaults
so ~/Dotfiles/vim/config/defaults.vimrc

" Source plugins
so ~/Dotfiles/vim/config/plugins.vimrc

" Source key mappings
so ~/Dotfiles/vim/config/mappings.vimrc

" Source customs
so ~/Dotfiles/vim/config/customs.vimrc

" Source statusline customization
so ~/Dotfiles/vim/config/statusline.vimrc
