source ~/Dotfiles/zsh/zsh_init.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source ~/.custom_paths

source ~/.tokens
if [ -e /Users/jibone/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/jibone/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
