# -----------------------------------------------------------------
# .bash_profile

export LC_ALL=en_US.UTF-8

# Hello message ---------------------------------------------------
echo -ne "Kernal Information: "; uname -smr
echo -ne "Uptime: "; uptime
echo -ne "Server time is: "; date
echo -e "Ghock and Gholl!"

export LC_ALL=en_US.UTF-8

# Source .bashrc --------------------------------------------------
source ~/.bashrc

# Source .tokens --------------------------------------------------
source ~/.tokens

# Source .gopath --------------------------------------------------
source ~/.gopath
if [ -e /Users/jibone/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/jibone/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
